language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -UI pip==7.1.2
  - pip install -r requirements.txt -r requirements-test.txt
  - python setup.py install

# command to run tests
script: ./script/test -vv
